version: '3'
services:
  elasticsearch:
    build: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
volumes:
  elasticsearch_data:
